"use client";

import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import "react-loading-skeleton/dist/skeleton.css";
import { ClerkProvider } from "@clerk/nextjs";
import { CartContext } from "./_context/CartContext";
import { useState } from "react";

const geistSans = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart, setCart] = useState([]);

  return (
    <ClerkProvider
      appearance={{
        elements: {
          formButtonPrimary: "bg-black text-white",
        },
      }}
    >
      <CartContext.Provider value={{ cart, setCart }}>
        <html lang="en">
          <body>
            <Header />
            {children}
            <Footer />
          </body>
        </html>
      </CartContext.Provider>
    </ClerkProvider>
  );
}
